name: mythic_todo
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.1
  get_it: ^7.2.0
  path: ^1.8.1
  shared_preferences: ^2.0.15
  sqflite: ^2.0.2+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/onboarding_logo_one.svg
    - assets/images/onboarding_logo_two.svg
    - assets/images/onboarding_background_one.svg
    - assets/images/onboarding_background_two.svg
    - assets/images/splash_screen_background.svg
    - assets/images/app_logo.svg
    - assets/images/app_icon.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Light.ttf
          weight: 300
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
