// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClzwrNXkTC1mZhlj-eyv2O6A8SsemZqyo',
    appId: '1:208559165492:web:24c3bebff8bf33a835ba61',
    messagingSenderId: '208559165492',
    projectId: 'mythictodo-cf582',
    authDomain: 'mythictodo-cf582.firebaseapp.com',
    storageBucket: 'mythictodo-cf582.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB45Pv_DY0YL-vxJH0qz2QB8PRVedtalCE',
    appId: '1:208559165492:android:181582f68c5890b535ba61',
    messagingSenderId: '208559165492',
    projectId: 'mythictodo-cf582',
    storageBucket: 'mythictodo-cf582.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCddwLHPFgrV9IFwCnTzC9tdOm4Qjk57AM',
    appId: '1:208559165492:ios:eab55206a9197c3e35ba61',
    messagingSenderId: '208559165492',
    projectId: 'mythictodo-cf582',
    storageBucket: 'mythictodo-cf582.appspot.com',
    iosClientId: '208559165492-rhjt4debqj48d7o4oot2qgm62mjdvq9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.mythicTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCddwLHPFgrV9IFwCnTzC9tdOm4Qjk57AM',
    appId: '1:208559165492:ios:eab55206a9197c3e35ba61',
    messagingSenderId: '208559165492',
    projectId: 'mythictodo-cf582',
    storageBucket: 'mythictodo-cf582.appspot.com',
    iosClientId: '208559165492-rhjt4debqj48d7o4oot2qgm62mjdvq9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.mythicTodo',
  );
}
