name: Release
on:
  push:
    branches: [master]
    paths-ignore:
      - '*/README.md'
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
