name: Release
on:
  push:
    branches: [main]
    paths-ignore:
      - '*/README.md'
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - uses: ncipollo/release-action@v2
        with:
          artifacts: "build/app/outputs/flutter-apk/.apk"
          token: $
